### ISSUE TITLE
Strings can be tricky sometimes中"ASCII letters"的翻译

### ISSUE THREAD

**Issue by z666pr** [true1023/Crazy-Python#2]
感觉原文

>Strings that are not composed of ASCII letters, digits or underscores, are not interned. 

中的 **ASCII letters** 翻译为 **ASCII字母** 更为贴切，翻译成 **ASCII字符** 有些不合适

**Comment by l00159860** [comment]
是的，我也有这个疑问。看代码确实指的是ASCII表中的字母。

**Comment by true1023** [comment]
确实，已更正
