### ISSUE TITLE
删除正在迭代中的列表项中一个疑问

### ISSUE THREAD

**Issue by Lxie111** [true1023/Crazy-Python#4]
<删除正在迭代中的列表项>中
list_3为什么能全部删除，没有讲解原因？
为什么在浅复制后，不会出现list_2中的结果？

**Comment by true1023** [comment]
> <删除正在迭代中的列表项>中
> list_3为什么能全部删除，没有讲解原因？
> 为什么在浅复制后，不会出现list_2中的结果？

list_3[:] 后并不是简单的指针复制，会出现内存地址完全不同的两个object
